# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode
#new change - with artifacts
trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- task: CmdLine@2
  inputs:
    script: 'pwd && ls -R'
# - task: Xcode@5
#   inputs:
#     actions: 'build'
#     scheme: 'calculator'
#     sdk: 'iphoneos'
#     configuration: 'Release'
#     xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
#     xcodeVersion: 10 # Options: 8, 9, 10, default, specifyPath
# - task: Xcode@5
#   inputs:
#     actions: 'test'
#     scheme: 'calculator'
#     sdk: 'iphoneos'
#     configuration: 'Release'
#     xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
#     xcodeVersion: 10 # Options: 8, 9, 10, default, specifyPath

- task: CmdLine@2
  inputs:
    script: 'xcodebuild build-for-testing -scheme $(project) -workspace *.xcodeproj/project.xcworkspace build CODE_SIGNING_ALLOWED=NO'

- task: CmdLine@2
  inputs:
    script: 'rm -rf /tmp/Payload'

- task: CmdLine@2
  inputs:
    script: 'sh app2ipa.sh ~/Library/Developer/Xcode/DerivedData/$(project)*/Build/Products/Debug-iphoneos $(project)'

# - task: CmdLine@2
#   inputs:
#     script: 'cd ~/Library/Developer/Xcode/DerivedData/calculator*/Build/Products/Release-iphoneos && cp -r . /tmp/Payload && cp -r calculatorUITests-Runner.app /tmp && ls -R '

# - task: CmdLine@2
#   inputs:
#     script: 'cd /tmp && ls -R'

# - task: CmdLine@2
#   inputs:
#     script: 'cd /tmp/Payload && rm -rf *-Runner.app && rm -rf *module && rm -rf *dSYM'

# - task: CmdLine@2
#   inputs:
#     script: 'cd /tmp && ls -R'

# - task: CmdLine@2
#   inputs:
#     script: 'cd /tmp && zip /tmp/calculator.ipa ./Payload'
# - task: CmdLine@2
#   inputs:
#     script: 'cd /tmp/calculatorUITests-Runner.app/plugins && zip -r ../../calculatorUITests.zip *'

- task: CmdLine@2
  inputs:
    script: 'ls -R /tmp'

- task: CmdLine@2
  inputs:
    script: 'echo $(build.artifactStagingDirectory)'

- task: CmdLine@2
  inputs:
    script: 'rm -rf /tmp/*.app'

- task: CmdLine@2
  inputs:
    script: 'cp -r /tmp/$(project)* $(build.artifactStagingDirectory)'

- task: CmdLine@2
  inputs:
    script: 'ls -R /tmp'

- task: PublishBuildArtifacts@1
- task: CmdLine@2
  inputs:
    script: 'pwd && ls -R'