# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode
#new change
trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- task: CmdLine@2
  inputs:
    script: 'pwd && ls -R'
- task: Xcode@5
  inputs:
    actions: 'build-for-testing'
    scheme: 'calculator'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
# - task: CmdLine@2
#   inputs:
#     script: 'xcodebuild build-for-testing -scheme calculator -workspace **/*.xcodeproj/project.xcworkspace'

- task: CmdLine@2
  inputs:
    script: 'cd ~/Library/Developer/Xcode/DerivedData/calculator*/Build/Products/Release-iphoneos && cp -r . /tmp/Payload && cp -r calculatorUITests-Runner.app /tmp && ls -R '

- task: CmdLine@2
  inputs:
    script: 'cd /tmp && ls -R'

- task: CmdLine@2
  inputs:
    script: 'cd /tmp && rm -rf *-Runner.app && rm *module && rm *dSYM'

- task: CmdLine@2
  inputs:
    script: 'cd /tmp && ls -R'

# - task: CmdLine@2
#   inputs:
#     script: 'cp -r calculator.app /tmp/Payload/'

- task: CmdLine@2
  inputs:
    script: 'cd /tmp && zip /tmp/calculator.ipa /Payload'
- task: CmdLine@2
  inputs:
    script: 'cd /tmp && zip calculatorUITests-Runner.zip calculatorUITests-Runner.app'

- task: CmdLine@2
  inputs:
    script: 'ls -R /tmp'

- task: CmdLine@2
  inputs:
    script: 'echo $(build.artifactStagingDirectory)'

- task: CmdLine@2
  inputs:
    script: 'cp -r /tmp/calculator* $(build.artifactStagingDirectory)'

# - task: CopyFiles@2
#   inputs:
#     contents: '~/Library/Developer/Xcode/DerivedData/calculator/Build/Products/Deployment/*.app'
#     targetFolder: '$(build.artifactStagingDirectory)'
# - task: CopyFiles@2
#   inputs:
#     contents: '**/*-Runner.zip'
#     targetFolder: '$(build.artifactStagingDirectory)'
- task: PublishBuildArtifacts@1
- task: CmdLine@2
  inputs:
    script: 'pwd && ls -R'