pool:
  vmImage: 'macOS-10.13'

variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
- task: CmdLine@2
  inputs:
    script: 'ls -R'
- task: CmdLine@2
  inputs:
    script: 'xcodebuild build-for-testing -scheme calculator -workspace *.xcodeproj/project.xcworkspace'

- task: CmdLine@2
  inputs:
    script: 'ls -R'